Repository php-amqplib/php-amqplib, pull requests merged in 2019-10, with the labels that each got.

#745 Remove phpDocumentator from dev dependencies
  .gitignore
  Makefile
  composer.json
Labels: chore

#740 Update amqp_connect_multiple_hosts.php
  demo/amqp_connect_multiple_hosts.php
Labels: bug

#746 Update version number to 2.10
  PhpAmqpLib/Connection/AbstractConnection.php
Labels: chore

#749 Add support for PLAIN authentication method
  PhpAmqpLib/Connection/AMQPSocketConnection.php
  PhpAmqpLib/Connection/AMQPStreamConnection.php
  PhpAmqpLib/Connection/AbstractConnection.php
  docker-compose.yaml
  tests/Functional/Channel/DirectExchangeTest.php
  tests/Functional/Channel/TopicExchangeTest.php
  tests/Functional/Connection/ConnectionAuthTest.php
Labels: feature

#753 Fix AMQPTimeoutException handling
  PhpAmqpLib/Connection/AbstractConnection.php
Labels: bug
