Repository php-amqplib/php-amqplib, pull requests merged in 2020-08, with the labels that each got.

#815 Add signal-based heartbeat option
  PhpAmqpLib/Connection/AbstractConnection.php
  PhpAmqpLib/Connection/Heartbeat/PCNTLHeartbeatSender.php
  PhpAmqpLib/Wire/IO/AbstractIO.php
  README.md
  demo/amqp_consumer_pcntl_heartbeat.php
  tests/Functional/SignalHeartbeatTest.php
  tests/Unit/Connection/Heartbeat/PCNTLHeartbeatSenderTest.php
Labels: feature

#817 AbstractIO::select() never returns false
  PhpAmqpLib/Wire/AMQPReader.php
Labels: chore

#816 Tidy up CI configuration
  .travis.yml
Labels: chore

#812 add missing timeout param for connection handshake response
  PhpAmqpLib/Connection/AbstractConnection.php
Labels: bug

#785 Enable TLS SNI by setting peer_name to $host in $ssl_options
  PhpAmqpLib/Connection/AMQPSSLConnection.php
Labels: enhancement

#819 use simple output instead of STDOUT in debug helper
  PhpAmqpLib/Helper/DebugHelper.php
Labels: bug
