Repository php-amqplib/php-amqplib, pull requests merged in 2021-02, with the labels that each got.

#874 fix annotation when AMQPTable is allowed variable type
  PhpAmqpLib/Channel/AMQPChannel.php
  PhpAmqpLib/Helper/Protocol/Protocol080.php
  PhpAmqpLib/Helper/Protocol/Protocol091.php
  PhpAmqpLib/Wire/Constants080.php
  spec/parser.php
Labels: bug

#875 Add support for next major version of phpseclib/phpseclib
  .github/workflows/phpunit.yml
  PhpAmqpLib/Helper/BigInteger.php
  PhpAmqpLib/Wire/AMQPDecimal.php
  PhpAmqpLib/Wire/AMQPReader.php
  PhpAmqpLib/Wire/AMQPWriter.php
  PhpAmqpLib/Wire/AbstractClient.php
  composer.json
Labels: enhancement

#882 feat(Composer) run test composer 2.
  .github/workflows/phpunit.yml
Labels: tests

#888 fix ValueError on closed or broken socket
  PhpAmqpLib/Wire/IO/AbstractIO.php
  PhpAmqpLib/Wire/IO/SocketIO.php
  PhpAmqpLib/Wire/IO/StreamIO.php
  tests/Unit/Wire/IO/SocketIOTest.php
  tests/Unit/Wire/IO/StreamIOTest.php
Labels: bug

#897 Drop deprecated things
  PhpAmqpLib/Connection/AMQPConnection.php
  PhpAmqpLib/Connection/AMQPLazyConnection.php
  PhpAmqpLib/Connection/AMQPLazySocketConnection.php
  PhpAmqpLib/Connection/AbstractConnection.php
  PhpAmqpLib/Exception/AMQPChannelException.php
  PhpAmqpLib/Exception/AMQPConnectionException.php
  PhpAmqpLib/Exception/AMQPException.php
  PhpAmqpLib/Exception/AMQPProtocolConnectionException.php
  PhpAmqpLib/Wire/AMQPAbstractCollection.php
  PhpAmqpLib/Wire/IO/AbstractIO.php
  tests/Functional/AbstractConnectionTest.php
  tests/Functional/FileTransferTest.php
Labels: chore

#893 Allow to use SSL connection as lazy
  PhpAmqpLib/Connection/AMQPLazySSLConnection.php
Labels: feature
