Repository php-amqplib/php-amqplib, pull requests merged in 2022-03, with the labels that each got.

#981 getChannelId can return null
  PhpAmqpLib/Channel/AbstractChannel.php
Labels: chore

#975 unified configuration class and factory for all kinds of connection
  PhpAmqpLib/Connection/AMQPConnectionConfig.php
  PhpAmqpLib/Connection/AMQPConnectionFactory.php
  PhpAmqpLib/Connection/AMQPLazyConnection.php
  PhpAmqpLib/Connection/AMQPLazySSLConnection.php
  PhpAmqpLib/Connection/AMQPLazySocketConnection.php
  PhpAmqpLib/Connection/AMQPSSLConnection.php
  PhpAmqpLib/Connection/AMQPSocketConnection.php
  PhpAmqpLib/Connection/AMQPStreamConnection.php
  PhpAmqpLib/Connection/AbstractConnection.php
  tests/Functional/AbstractConnectionTest.php
Labels: enhancement

#977 Channel method for continuous message consumption
  PhpAmqpLib/Channel/AMQPChannel.php
  PhpAmqpLib/Connection/AbstractConnection.php
  PhpAmqpLib/Wire/IO/AbstractIO.php
  PhpAmqpLib/Wire/IO/SocketIO.php
  PhpAmqpLib/Wire/IO/StreamIO.php
  demo/amqp_consumer.php
  demo/amqp_consumer_exclusive.php
  demo/amqp_consumer_fanout_1.php
  demo/amqp_consumer_fanout_2.php
  demo/amqp_consumer_pcntl_heartbeat.php
  demo/basic_nack.php
  demo/delayed_message.php
Labels: feature

#983 Throw connection exceptions on batch publish
  PhpAmqpLib/Channel/AMQPChannel.php
  tests/Unit/Channel/AMQPChannelTest.php
  tests/Unit/Test/TestChannel.php
Labels: bug
