Repository php-amqplib/php-amqplib, pull requests merged in 2022-10, with the labels that each got.

#1025 Upgrade toxiproxy, enable all tests on CI
  .github/workflows/changelog.yml
  .github/workflows/code-style.yml
  .github/workflows/documentation.yml
  .github/workflows/phpunit.yml
  docker-compose.yaml
  tests/Functional/AbstractConnectionTest.php
  tests/Functional/Connection/ConnectionClosedTest.php
Labels: chore

#1024 Fix heartbeat negotiation
  PhpAmqpLib/Connection/AbstractConnection.php
  tests/Functional/Connection/ConnectionCreationTest.php
Labels: bug

#1026 Allow set socket send buffer size
  PhpAmqpLib/Connection/AMQPConnectionConfig.php
  PhpAmqpLib/Connection/AMQPSocketConnection.php
  PhpAmqpLib/Wire/IO/AbstractIO.php
  PhpAmqpLib/Wire/IO/SocketIO.php
  tests/Functional/AbstractConnectionTest.php
  tests/Unit/Wire/IO/SocketIOTest.php
Labels: feature

#1028 Update codecov action to latest version
  .github/workflows/phpunit.yml
Labels: chore

#1030 Allow disable heartbeats from client side
  PhpAmqpLib/Connection/AbstractConnection.php
  PhpAmqpLib/Wire/IO/AbstractIO.php
Labels: bug

#1033 Missing PHPDoc param in AbstractConnection constructor
  PhpAmqpLib/Connection/AbstractConnection.php
Labels: chore

#1031 Split buffer and IO readers into separate classes
  PhpAmqpLib/Channel/AMQPChannel.php
  PhpAmqpLib/Channel/AbstractChannel.php
  PhpAmqpLib/Connection/AbstractConnection.php
  PhpAmqpLib/Wire/AMQPBufferReader.php
  PhpAmqpLib/Wire/AMQPByteStream.php
  PhpAmqpLib/Wire/AMQPIOReader.php
  PhpAmqpLib/Wire/AMQPReader.php
  PhpAmqpLib/Wire/AMQPWriter.php
  tests/Unit/Message/AMQPMessageTest.php
  tests/Unit/Test/TestConnection.php
  tests/Unit/Wire/AMQPReaderTest.php
  tests/Unit/WireTest.php
Labels: chore

#1035 Add the ability to set the connection name through AMQPConnectionConfig
  PhpAmqpLib/Connection/AMQPConnectionConfig.php
  PhpAmqpLib/Connection/AMQPSSLConnection.php
  PhpAmqpLib/Connection/AMQPSocketConnection.php
  PhpAmqpLib/Connection/AMQPStreamConnection.php
  PhpAmqpLib/Connection/AbstractConnection.php
  tests/Unit/Connection/AMQPConnectionConfigTest.php
Labels: feature
