Repository php-amqplib/php-amqplib, pull requests merged in 2022-02, with the labels that each got.

#971 Custom PCNTL Heartbeat Sender
  PhpAmqpLib/Connection/Heartbeat/AbstractSignalHeartbeatSender.php
  PhpAmqpLib/Connection/Heartbeat/PCNTLHeartbeatSender.php
  PhpAmqpLib/Connection/Heartbeat/SIGHeartbeatSender.php
  tests/Functional/Connection/Heartbeat/SIGHeartbeatSenderTest.php
Labels: feature

#972 Add $restart_syscalls = true explicitly when calling pcntl_signal to avoid crashing SQL Server connections
  PhpAmqpLib/Connection/Heartbeat/PCNTLHeartbeatSender.php
Labels: bug

#976 Propagate real exceptions
  PhpAmqpLib/Channel/AMQPChannel.php
  PhpAmqpLib/Channel/AbstractChannel.php
  PhpAmqpLib/Connection/AbstractConnection.php
Labels: enhancement
