Repository php-amqplib/php-amqplib, pull requests merged in 2023-10, with the labels that each got.

#1116 TCP keepalive for TLS connections
  PhpAmqpLib/Connection/AMQPConnectionConfig.php
  PhpAmqpLib/Connection/AMQPConnectionFactory.php
  PhpAmqpLib/Connection/AMQPSSLConnection.php
  PhpAmqpLib/Connection/AMQPStreamConnection.php
  PhpAmqpLib/Wire/IO/StreamIO.php
  tests/Functional/AbstractConnectionTest.php
  tests/Functional/Connection/SSLConnectionTest.php
  tests/Unit/Connection/AMQPConnectionConfigTest.php
Labels: enhancement

#1122 drop support for PHP7.1
  .github/workflows/phpunit.yml
  PhpAmqpLib/Connection/AMQPConnectionConfig.php
  appveyor.yml
  composer.json
  docker/php/Dockerfile
Labels: chore

#1126 Add Additional Test Coverage for AMQPConnectionConfig Class
  tests/Functional/AbstractConnectionTest.php
  tests/Functional/Bug/Bug256Test.php
  tests/Functional/Channel/ChannelConsumeTest.php
  tests/Functional/Connection/AMQPStreamConnectionTest.php
  tests/Functional/Connection/ConnectionClosedTest.php
  tests/Functional/Connection/ConnectionCreationTest.php
  tests/Functional/Connection/ConnectionUnresponsiveTest.php
  tests/Functional/Connection/Heartbeat/PCNTLHeartbeatSenderTest.php
  tests/Functional/Connection/Heartbeat/SIGHeartbeatSenderTest.php
  tests/Functional/Connection/Heartbeat/SignalHeartbeatTest.php
  tests/Functional/Connection/SSLConnectionTest.php
  tests/Unit/Connection/AMQPConnectionConfigTest.php
Labels: tests

#1133 Updated docblock
  PhpAmqpLib/Channel/AMQPChannel.php
  PhpAmqpLib/Helper/Protocol/Protocol091.php
Labels: documentation

#1132 Only call fwrite() if select() said the fd is ready.
  PhpAmqpLib/Wire/IO/SocketIO.php
  PhpAmqpLib/Wire/IO/StreamIO.php
Labels: enhancement
